plugins {
    id 'com.android.application' version '8.8.2'
    id 'org.jetbrains.kotlin.android' version '2.1.21'
    id 'org.jetbrains.kotlin.plugin.serialization' version "2.1.0"
}

android {
    namespace 'com.ustadmobile.orbotmeshrabiyaintegration'
    compileSdk 34

    defaultConfig {
        applicationId "com.ustadmobile.orbotmeshrabiyaintegration"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    packagingOptions {
        resources {
            excludes += ['META-INF/versions/9/OSGI-INF/MANIFEST.MF', 'META-INF/MANIFEST.MF']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled false
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':Meshrabiya:lib-meshrabiya')
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.datastore:datastore-preferences:1.1.7'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'org.jetbrains.kotlin:kotlin-test:2.1.21'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.10.3'
    testImplementation 'io.mockk:mockk:1.13.7'
    testImplementation 'androidx.test:core:1.5.0'
    testImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation 'androidx.security:security-crypto:1.1.0-alpha06'
} 
